# Generated by Django 3.0.6 on 2020-05-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectIntApp', '0003_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='content',
            new_name='status',
        ),
    ]
